project_id = "bgcnvyoseexfmrynqbfb"

[functions.create-user]
verify_jwt = false

[functions.upload-media]
verify_jwt = false

[functions.device-detection]
verify_jwt = false

[functions.import-stores]
verify_jwt = false

[functions.product-lookup]
verify_jwt = false
