project_id = "bgcnvyoseexfmrynqbfb"

[functions.canva-auth]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.upload-media]
verify_jwt = false

[functions.device-detection]
verify_jwt = false

[functions.import-stores]
verify_jwt = false

[functions.product-lookup]
verify_jwt = false

[functions.product-enrich]
verify_jwt = false

[functions.delete-media]
verify_jwt = false

[functions.import-product-catalog]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.inky-landing]
verify_jwt = false

[functions.inky-insights]
verify_jwt = false
